books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views
# поиск
from modules.search.views import TagJson
from app.book.views import *
#Переопределение названий
from django.contrib import admin
admin.site.site_title = "books"
admin.site.site_header = "books" 
admin.site.site_url = "/" 

urlpatterns = [
    path('book-upload/', views.book_upload, name='book-upload'),
    path('book_admin/', admin.site.urls),
	path('logout/', views.logout, name='logout'),

    #поиск
    path('hashtag.json', TagJson.as_view()),

    # path('index', views.index,  name='index'),

    path('', views.home,  name='home'),
	path('allbook/', views.allbook,  name='allbook'),
    path('login/', views.login,  name='login'),
	path('register/', views.register,  name='register'),
    path('', include('app.book.urls')),
	
    path("ckeditor5/", include('django_ckeditor_5.urls')),
	
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'books.views.handler404'
handler500 = 'books.views.handler500'
handler403 = 'books.views.handler403'
handler400 = 'books.views.handler400'

app/book/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 
from django.core.exceptions import ValidationError 
from django.forms.fields import EmailField 
from django.forms.forms import Form 
from .models import Book
import os
from bs4 import BeautifulSoup

class book_reader:
    def __init__(self, file):
        self.file = file
        self.book = []
        with open(self.file, 'r', encoding='utf-8') as file:
            file = file.readlines()
            _book = []
            for line in file:
                _book.append(line.lstrip())
            for line in file:
                _book.append(line.replace('<p>', '').replace('</p>','\n'))
            for line in _book:
                self.book.append(line.strip('\n'))

    @property
    def get_description(self):
        _description = []
        for line in self.book:
            if line.startswith('<description>'):
                line_index = self.book.index(line)
                for line in self.book[line_index:]:
                    _description.append(line)
                    if line.startswith('</description>'):
                        break

        description = {}
        for line in _description:
            if line.startswith('<book-name>'):
                description['book-title'] = line.lstrip('<book-name>').rstrip('</book-name>')
            elif line.startswith('<book-title>'):
                description['book-title'] = line.lstrip('<book-title>').rstrip('</book-title>')
            elif line.startswith('<author>'):
                a = _description.index(line)
                for i in self.book[a:]:
                    if i.startswith('<first-name>'):
                        description['autor-first-name'] = i.lstrip('<first-name>').rstrip('</first-name>')
                    if i.startswith('<middle-name>'):
                        description['autor-middle-name'] = i.lstrip('<middle-name>').rstrip('</middle-name>')
                    if i.startswith('<last-name>'):
                        description['autor-last-name'] = i.lstrip('<last-name>').rstrip('</last-name>')
                    if i.startswith('</author>'):
                        break
            elif line.startswith('<annotation>'):
                annotation = []
                line_index = self.book.index(line)
                for line in self.book[line_index:]:
                    annotation.append(line)
                    if line.startswith('</annotation>'):
                        break
                description['annotation'] = ''.join(annotation).replace('<empty-line/>', '\n').replace('<annotation>', '').replace('</annotation>', '')

        return description

    def get_chapters_title(self):
        chapters = []
        for index, value in enumerate(self.book):
            if value.startswith('<title>'):
                a = {index : self.book[index+1].lstrip('<p>').rstrip('</p>').lstrip('strong>').rstrip('</strong')}
                chapters.append(a)

        return chapters
class BookUploadForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name_block', 'book_slug', 'book_cat', 
                   
                     'image','image2', 
                     'opisanie_mini',
                    #  'price', 'old_price', 
                     'file']
        
        # opisanie_mini = forms.CharField(widget=forms.Textarea(attrs={
        #     'rows': 3,
        #     # 'cols': 80,
        #     'class' : 'form-control',
        # }))

        # name_block = forms.CharField(widget=forms.TextInput(attrs={
        #     'class' : 'form-control',
        # }))
        # book_slug = forms.CharField(widget=forms.TextInput(attrs={
        #     'class' : 'form-control',
        # }))


class UserForm(UserCreationForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ('first_name','last_name', 'username', 'email', 'password1' ,'password2' )

templates/default/allbook.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
{% include "header.html" %}

<div class="wrap-breadcrumb parallax-breadcrumb">
	<div class="container"></div>
</div>

<div class="container">

	<div class="row">

		{% include "left.html" %}

		<div id="content" class="col-sm-9  single-blog">
			<ul class="breadcrumb">

				<li><a href="/"><i class="fa fa-home"></i></a></li>

				<li>Все книги</li>

			</ul>
			<h1>Все книги</h1>

			
		
<ol style="font-size: 18px;">
			{% for book in allbook.all %}
			
				<li style="margin-bottom: 10px"><a href="{{book.get_absolute_url}}">{{book.name_block|safe}}</a></li>					
			{% empty %}
					<p style="font-size: 16px">Нет книг</p>
			{% endfor %}
		</ol>

		
		</div>
	</div>
</div>


{% include "footer.html" %}
{% endblock %}

templates/default/base.html
{% load static %}
<!doctype html>
<html>
<head>
  	<meta charset="utf-8">
  	<meta name="format-detection" content="telephone=no"/>
  	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">


	  <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    {% block robots_zakrit %}{% endblock %}


 <!-- favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/media/favicon/apple-icon-57x57.png" >
    <link rel="apple-touch-icon" sizes="60x60" href="/media/favicon/apple-icon-60x60.png" >
    <link rel="apple-touch-icon" sizes="72x72" href="/media/favicon/apple-icon-72x72.png" >
    <link rel="apple-touch-icon" sizes="76x76" href="/media/favicon/apple-icon-76x76.png" >
    <link rel="apple-touch-icon" sizes="114x114" href="/media/favicon/apple-icon-114x114.png" >
    <link rel="apple-touch-icon" sizes="120x120" href="/media/favicon/apple-icon-120x120.png" >
    <link rel="apple-touch-icon" sizes="144x144" href="/media/favicon/apple-icon-144x144.png" >
    <link rel="apple-touch-icon" sizes="152x152" href="/media/favicon/apple-icon-152x152.png" >
    <link rel="apple-touch-icon" sizes="180x180" href="/media/favicon/apple-icon-180x180.png" >
    <link rel="icon" type="image/png" sizes="192x192"  href="/media/favicon/android-icon-192x192.png" >
    <link rel="icon" type="image/png" sizes="32x32" href="/media/favicon/favicon-32x32.png" >
    <link rel="icon" type="image/png" sizes="96x96" href="/media/favicon/favicon-96x96.png" >
    <link rel="icon" type="image/png" sizes="16x16" href="/media/favicon/favicon-16x16.png" >
    <link rel="manifest" href="/media/favicon/manifest.json" >
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/media/favicon/ms-icon-144x144.png" >
    <meta name="theme-color" content="#ffffff">
    <!-- / favicon -->


    <meta property="og:locale" content="ru_RU">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% block og_title %}{% endblock %}">
    <meta property="og:description" content="{% block og_description %}{% endblock %}">
    <meta property="og:url" content="{% block og_url %}{% endblock %}">
    <meta property="og:site_name" content="Books">
    <meta property="article:modified_time" content="2022-01-11T09:43:32+00:00">
    <meta property="og:image" content="{% block og_image %}{% endblock %}">
    <meta property="og:image:width" content="512">
    <meta property="og:image:height" content="512">
    <meta property="og:image:type" content="image/png">
    <meta name="twitter:card" content="summary_large_image">


  <link href="{% block image_src %}{% endblock %}" rel="image_src"/>


  <link rel="canonical" href="{% block canonical %}{% endblock %}"/>



<script src="/media/js/jquery/jquery-2.1.1.min.js" type="text/javascript"></script>
<script src="/media/js/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<link href="/media/js/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
<link href="/media/css/stylesheet.css" rel="stylesheet" />

<!-- Codezeel - Start -->
<link rel="stylesheet" type="text/css" href="/media/js/jquery/magnific/magnific-popup.css" />
<link rel="stylesheet" type="text/css" href="/media/css/carousel.css" />
<link rel="stylesheet" type="text/css" href="/media/css/custom.css" />
<link rel="stylesheet" type="text/css" href="/media/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/media/css/lightbox.css" />
<link rel="stylesheet" type="text/css" href="/media/css/animate.css" />


<link href="style.html" type="text/css" rel="style.rel" media="style.media" />
<link href="style.html" type="text/css" rel="style.rel" media="style.media" />


<link href="/media/js/jquery/swiper/css/swiper.min.css" type="text/css" rel="stylesheet" media="screen" />
<link href="/media/js/jquery/swiper/css/opencart.css" type="text/css" rel="stylesheet" media="screen" />
<script src="/media/js/jquery/swiper/js/swiper.jquery.js" type="text/javascript"></script>


<script type="text/javascript" src="/media/js/custom.js"></script>
<script type="text/javascript" src="/media/js/jstree.min.js"></script>
<script type="text/javascript" src="/media/js/carousel.min.js"></script>
<script type="text/javascript" src="/media/js/codezeel.min.js"></script>
<script type="text/javascript" src="/media/js/jquery.custom.min.js"></script>
<script type="text/javascript" src="/media/js/jquery.formalize.min.js"></script>



<script type="text/javascript" src="/media/js/lightbox/lightbox-2.6.min.js"></script>
<script type="text/javascript" src="/media/js/tabs.js"></script>
<script type="text/javascript" src="/media/js/jquery.elevatezoom.min.js"></script>
<script type="text/javascript" src="/media/js/bootstrap-notify.min.js"></script>
<script type="text/javascript" src="/media/js/doubletaptogo.js"></script>
<script type="text/javascript" src="/media/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="/media/js/jquery/magnific/jquery.magnific-popup.min.js"></script>


<script src="/media/js/common.js" type="text/javascript"></script>




</head>

<body>





{% block content %}
{% endblock %}



</body>
</html>

templates/default/css.html
<style>


:root {
    --font-family-primary: "Segoe UI", system-ui, Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    --font-family-monospace: ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}


.people_card_block{
    padding: 10px;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: -o-flex;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    width: 450px;
    margin-bottom: 20px;
    border-radius: 40px;
    font-size: 14px;
}

.people_card_block_gender_m{
    background: #c3e4e1;
}
.people_card_block_gender_g{
    background: #d6acef;
}



.people_card_block_l{
    width: 100px;
    height: 100px;
    margin-right: 20px;
}
.people_card_block_l img{
    width: 100px;
    height: 100px;
    border-radius: 50%;
    object-fit: cover;
}
.people_card_block_r{
    width: calc(100% - 170px);
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    line-height: 1;
    height: max-content;
}

.people_card_block_line{
	display: flex;
    margin-bottom: 10px;
}
.people_card_block_line_lable{}
.people_card_block_line_val{
	font-weight: 600;
}


#header {
    width: auto;
    height: auto;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 40px;
    background: #417690;
    color: #fff;
}

#branding {
    display: flex;
}

#site-name {
    padding: 0;
    margin: 0;
    margin-inline-end: 20px;
    font-weight: 300;
    font-size: 1.5rem;
    color: var(--header-branding-color);
}

#site-name a:link, #site-name a:visited {
    color: #fff;
}

#user-tools {
    float: right;
    margin: 0 0 0 20px;
    text-align: right;
}

#user-tools, #logout-form button {
    padding: 0;
    font-weight: 300;
    font-size: 0.6875rem;
    letter-spacing: 0.5px;
    text-transform: uppercase;
}

#user-tools a, #logout-form button {
    border-bottom: 1px solid rgba(255, 255, 255, 0.25);
}

#header a:link, #header a:visited, #logout-form button {
    color: #fff;    text-decoration: none;   font-family: var(--font-family-primary);
}


div.breadcrumbs {
    background: #264b5d;
    padding: 10px 40px;
    border: none;
    color: #c4dce8;
    text-align: left;

    font-size: 0.875rem;
    font-family: var(--font-family-primary);
}
div.breadcrumbs a {
color: #fff;
    font-size: 0.875rem;
    font-family: var(--font-family-primary);
}


.container_wiki {
    margin-left: auto;
    margin-right: auto;
    max-width: 1300px;
    width: 100%;
    margin-bottom: 100px;
    font-family: Arial;
}

.container_wiki h1 {
    text-align: center;
    font-weight: normal;
    font-size: 40px;
    line-height: .9;
    margin-bottom: 20px;
    margin-top: 40px;
    margin-left: 2%;
    margin-right: 2%;
}

.container_wiki h2 {
    text-align: center;
    font-weight: normal;
    line-height: .9;
    margin-bottom:20px;
    margin-top: 40px;
    margin-left: 2%;
    margin-right: 2%;
}

.wiki_cat_wrp {

position: relative;
    padding-top: 14px;
    padding-bottom: 14px;
    padding-left: 10px;
    padding-right: 10px;
    text-align: center;
    color: #777;
    border: 1px solid #bbb;
    background-color: #f3f3f3;
    margin-top: 20px;
    margin-bottom: 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.wiki_cat_wrp_l {
    width: auto;
}
.wiki_cat_wrp_r {
        display: flex;
    justify-content: right;
}

.wiki_cat_wrp a {
    display: inline-block;
    font-family: Arial;
    font-size: 19px;
    padding-top: 2px;
    padding-bottom: 2px;
    margin-left: 5px;
    margin-right: 5px;
    padding-left: 2px;
    padding-right: 2px;
    color: #666;
    cursor: pointer;
    border-bottom: 1px solid transparent;
    text-decoration: none;
}

.wiki_cat_wrp a:hover {
        border-bottom: 1px dashed #666;
        opacity:0.8;
}

.wiki_cat_wrp a.active_url{
        border-bottom: 1px dashed #666;
}

.wiki_cat_wrp a.active_url:hover{
    opacity:1;
}

.task_block{
    width: 32.33333333%;
    margin-left: .5%;
    margin-right: .5%;
    min-height: 63px;
    color: #245f94;
    text-align: center;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    margin-bottom: 10px;
    background-color: #f9f9f9;
    border: 1px dashed #8ca5cf;
    text-decoration: none;
    position: relative;
        max-height: 350px;
        transition: all 0.2s;
}

.task_block:hover{
   
    scale: 102%;
}

.task_block a {
text-decoration: none;
    display: block;
    padding-top: 20px;
    padding-bottom: 20px;
    padding-left: 15px;
    padding-right: 15px;
}

.task_block_name{
display: block;
    color: #203b69;
    font-family: "Times New Roman";
    font-size: 21px;
    margin-bottom: 15px;
}
.task_block_opisanie{
    display: block;
    margin-bottom: 5px;
    font-family: Arial;
    font-size: 15px;
    /* -webkit-transform: scaleY(1.1);
    -moz-transform: scaleY(1.1);
    -ms-transform: scaleY(1.1);
    transform: scaleY(1.1);
    line-height: 1.1; */
    color: #245f94;
    text-align: left;
}


.task_wrap {
        display: flex;
    flex-direction: row;
    justify-content: flex-start;
    flex-wrap: wrap;
    padding-left: 0;
    margin-top: 0;
    text-align: left;
    margin-bottom: 20px;
    margin-left: -0.5%;
    margin-right: -0.5%;
}


pre.prettyprint {
    margin: 0;
    margin-bottom: 10px;
    background: #ebebeb;
    border: 0;
    /* border-radius: 10px; */
    padding: 10px;
    padding-left: 20px;
    text-align: left;
    border-left: 1px dashed #ccc;
    background: repeating-linear-gradient(to bottom, transparent, transparent 10px, #f4f4f4 10px, #f4f4f4 11px),repeating-linear-gradient(to right, transparent, transparent 10px, #f4f4f4 10px, #f4f4f4 11px);
    background-clip: padding-box;
    margin: 0 0 2px 0;
    padding: 15px 0 15px 44px;
}


.travel_wrap{
      margin-left: auto;
    margin-right: auto;
    max-width: 1400px;
    width: 100%;
    margin-bottom: 100px;
    font-family: Arial;  
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: -o-flex;
    display: flex;
    flex-wrap: wrap;
    
}

.travel_card{
    background: #f1f1f1;
    border-radius: 20px;
    display: flex;
    margin-bottom: 1.875rem;
    min-height: 8.75rem;
    padding: 20px;
    position: relative;
    margin-left: 20px;
    margin-right: 20px;
    width: 40%;
}
.travel_card_l {
    width: 50%;
}
.travel_card_r {
    padding-left: 10px;
    width: 50%;
}

.travel_card_r img{
        width: 100%;
        border-radius: 7px 7px 7px 7px;
        -moz-border-radius: 7px 7px 7px 7px;
        -webkit-border-radius: 7px 7px 7px 7px;
        
}

.travel_card_l_name {
    font-size: 24px;
    line-height: 1.2;
}

.travel_card_l_op {
    line-height: 1.5;
}



ol.linenums { margin-top: 0; margin-bottom: 0 }
li.L0,
li.L1,
li.L2,
li.L3,
li.L5,
li.L6,
li.L7,
li.L8 { list-style-type: none }
/* Alternate shading for lines */
li.L1,
li.L3,
li.L5,
li.L7,
li.L9 { background: #ececec }

.linenums li {
    list-style-type: decimal;
}


.h1_date {
    text-align: center;
    font-weight: 600;
    color: #777;
    margin-bottom: 20px;
}

.travelvideo_wrap{
    margin-top:0px;
    display: flex;  
    flex-wrap: wrap;
    gap: 10px;
}

.travelvideo_wrap a {
    width: 48.3%;

    height: 140px;  
        position: relative;
    border-radius: 7px;
    overflow: hidden;
}

.travelvideo_wrap img{
    width: 100%;
    height: 100%; 
}

.play-wrap {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 30px;
    height: 30px;
    margin-left: -15px;
    margin-top: -15px;
}

.yt_v_w_fon {
    background-size: cover;
    width: 100%;
    height: 100%;
}
.yt_v_w {
    /* width: 49%;
    width: 120px;
    height: 76px; */
    position: relative;
    width: 100%;
    height: 100%;
}

.travel_name {
    position: absolute;
    bottom: 0;
    background: rgba(0,0,0,0.5);
    width: 100%;
    text-align: center;
    color: #fff;
    padding: 5px 0;
    font-size: 12px;
    font-family: 'Roboto';
}

.play{
    width: 100%;
    height: 100%;
    background-image: url(/media/play.svg);
    background-size: contain;
}

.paginator_a {
    color: #2d2d38;
    font-size: 30px;
    color: #245f94;
}

.cateogory_midle_right_navigations {
width: calc(100% + 1px);
    text-align: center;
    margin: 0px 0;
   
    padding: 10px 20px;
  
    margin-left: -1px;
    margin-right: 20px;
    box-sizing: border-box;
    line-height: 1.4;
}
.paginator_wrapper {
    margin-bottom: 0px;
}
.paginator_current {
    margin-right: 15px;
    padding: 7px 15px 5px;
    position: relative;
    font-size: 30px;
    color: #245f94;
    text-align: center;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    margin-bottom: 10px;
    background-color: #f9f9f9;
    border: 1px dashed #8ca5cf;
}

.paginator_wrapper a {
    margin-right: 25px;
    text-decoration: none;
    color: #245f94;
    font-size: 30px;
}

.paginator_a_dots {
    margin-left: -10px;
    margin-right: 40px;
    font-size: 30px;
     color: #245f94;
}




{% include "search/search_style.css" %}

</style>

templates/default/register.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{book.name_block|safe}}{% endblock %}
{% block description %}{{book.name_block|safe}}{% endblock %}

{% block og_title %}{{book.name_block|safe}}{% endblock %}
{% block og_description %}{{book.name_block|safe}}{% endblock %}

{% block og_url %}{{ request.build_absolute_uri }}{% endblock %}
{% block image_src %}{% if book.image %}/media/{{book.image|safe}}{% else %}/media/zaglavka.png{% endif %}{% endblock %}
{% block og_image %}{% if book.image %}/media/{{book.image|safe}}{% else %}/media/zaglavka.png{% endif %}{% endblock %}


{% block canonical %}{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ book.get_absolute_url }}{% endblock %}


{% block content %}
{% include "header.html" %}

<style>
	.line {
		display: flex;
	}

	.line p {
		padding: 0 5px;
	}
</style>

<link href="/media/bootstrap-datetimepicker.min.css" type="text/css" rel="stylesheet" media="screen">
<script src="/media/moment.min.js" type="text/javascript"></script>
<script src="/media/moment-with-locales.min.js" type="text/javascript"></script>
<script src="/media/bootstrap-datetimepicker.min.js" type="text/javascript"></script>

<div class="wrap-breadcrumb parallax-breadcrumb">
	<div class="container"></div>
</div>

<div class="container">

	<div class="row">

		{% include "left.html" %}

		<div id="content" class="col-sm-9 productpage">
			<ul class="breadcrumb">

				<li><a href="/"><i class="fa fa-home"></i></a></li>


				<li>Регистрация</li>

			</ul>

			<!--  -->


		<h1>Регистрация Аккаунта</h1>
      <p>Если у вас уже есть учетная запись на нашем сайте, пожалуйста, войдите на 
	<a href="/login/">страницу входа</a> .</p>



{% if messages %} 
<ul> 
{% for message in messages %} 
<li>{{ message }}</li> 
{% endfor %} 
</ul> 
{% endif %} 




   


      <form action="/register/" method="post" enctype="multipart/form-data" class="form-horizontal">
		  {% csrf_token %}
        <fieldset id="account">
          <legend>Ваши персональные данные</legend>
          
		  <div class="form-group required">
            <label class="col-sm-2 control-label" for="input-firstname">Имя пользователя</label>
            <div class="col-sm-10">

			  <input type="text" name="username" maxlength="150" placeholder="Имя пользователя" autocapitalize="none" autocomplete="username" class="form-control" autofocus="" required="" aria-describedby="id_username_helptext" id="id_username">

               </div>
          </div>
          <div class="form-group required">
            <label class="col-sm-2 control-label" for="id_first_name">Имя</label>
            <div class="col-sm-10">
              <input type="text" name="first_name" value="" placeholder="Имя" id="id_first_name" class="form-control">

			
               </div>
          </div>
          <div class="form-group required">
            <label class="col-sm-2 control-label" for="id_last_name">Фамилия</label>
            <div class="col-sm-10">
              <input type="text" name="last_name" value="" placeholder="Фамилия" id="id_last_name" class="form-control">

			  
               </div>
          </div>
          <div class="form-group required">
            <label class="col-sm-2 control-label" for="id_email">Электронная почта</label>
            <div class="col-sm-10">
              <input type="email" name="email" value="" placeholder="Электронная почта" id="id_email" class="form-control">
			 
               </div>
          </div>
         
                  </fieldset>
        <fieldset>
          <legend>Ваш пароль</legend>
          <div class="form-group required">
            <label class="col-sm-2 control-label" for="input-password">Пароль</label>
            <div class="col-sm-10">
         
			    <input type="password" name="password1"  placeholder="Пароль" autocomplete="new-password" required="" class="form-control" aria-describedby="id_password1_helptext" id="id_password1">
               </div>
          </div>
          <div class="form-group required">
            <label class="col-sm-2 control-label" for="input-confirm">Подтвердить пароль</label>
            <div class="col-sm-10">
				
				<input type="password" name="password2" autocomplete="new-password" placeholder="Подтвердить пароль" class="form-control" required="" aria-describedby="id_password2_helptext" id="id_password2">

               </div>
          </div>
        </fieldset>
       
      



                <div class="buttons">
          <div class="pull-right">
                      
            <button type="submit" value="Продолжать" name="register" class="btn btn-primary">Продолжить</button>
          </div>
        </div>
              </form>



				
		</div>
	</div>
</div>


{% include "footer.html" %}
{% endblock %}