app/book/urls.py
#coding: utf-8

from django.urls import path, re_path
from app.book import views
from .views import *

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug>/', views.blog_full, name='blog_full'),
    path('catalog/<book_cat_slug>/', views.book_cat, name='book_cat'),
    path('catalog/<book_cat_slug>/<book_slug>/', views.book_full, name='book_full'),
	path('catalog/<book_cat_slug>/<book_slug>/prewie/', views.book_full_reader, name='book_full_reader'),
    path('<slug>/', views.prostopages, name='prostopages'),
]

books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views
# поиск
from modules.search.views import TagJson
from app.book.views import *
#Переопределение названий
from django.contrib import admin
admin.site.site_title = "books"
admin.site.site_header = "books" 
admin.site.site_url = "/" 

urlpatterns = [
    path('book-upload/', views.book_upload, name='book-upload'),
    path('book_admin/', admin.site.urls),
	path('logout/', views.logout, name='logout'),

    #поиск
    path('hashtag.json', TagJson.as_view()),

    # path('index', views.index,  name='index'),

    path('', views.home,  name='home'),
	path('allbook/', views.allbook,  name='allbook'),
    path('login/', views.login,  name='login'),
	path('register/', views.register,  name='register'),
    path('', include('app.book.urls')),
	
    path("ckeditor5/", include('django_ckeditor_5.urls')),
	
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'books.views.handler404'
handler500 = 'books.views.handler500'
handler403 = 'books.views.handler403'
handler400 = 'books.views.handler400'

app/book/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from datetime import datetime
from django.utils import timezone

from django_ckeditor_5.fields import CKEditor5Field

#картинка в админке
from django.utils.safestring import mark_safe


from sorl.thumbnail import get_thumbnail


#валидация рейтинга
from django.core.validators import MaxValueValidator, MinValueValidator

from django.db.models import Avg, Max, Min, Sum

from django.contrib.auth.models import User

# Категории книг

class Book_cat(models.Model):
	name_block = models.CharField(u'Название', max_length=255, null=True, blank=True)
	active = models.BooleanField(default=True,verbose_name='Активность',)
	nomer_id = models.IntegerField(u'Номер сортировки',  null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="Created at")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
	book_cat_slug = models.SlugField(unique=True, max_length=255,  verbose_name='Url', db_index=True)

	def __str__(self):
		return self.name_block

	# переопределение названий
	class Meta:
		verbose_name = "Категории книг"
		verbose_name_plural = "Категории книг"
		ordering = ["nomer_id"]

	def get_absolute_url(self):
		return "/catalog/%s/" % (self.book_cat_slug)
	
	def save(self, *args, **kwargs):
		if not self.book_cat_slug:
			lastid = Book_cat.objects.latest('id')
			self.book_cat_slug =  createslug(self.name_block)
		super(Book_cat, self).save(*args, **kwargs)





class Book_avtor (models.Model):
	name_block = models.CharField(u'Фамилия', max_length=255, unique=False, null=True, blank=True)
	name_block2 = models.CharField(u'Имя', max_length=255, unique=False, null=True, blank=True)
	name_block3 = models.CharField(u'Отчество', max_length=255, unique=False, null=True, blank=True)

	active = models.BooleanField(default=True,verbose_name='Активность',)
	created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="Created at")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
	template_name = models.CharField(
		('Выбор шаблона'),
		max_length=70,
		blank=True,
	)


	def __str__(self):
		if self.name_block and self.name_block2 and self.name_block3:
			return f"{self.name_block} {self.name_block2} {self.name_block3}"
		elif self.name_block and self.name_block2:
			return f"{self.name_block} {self.name_block2}"
		elif self.name_block2 and self.name_block3:
			return f"{self.name_block2} {self.name_block3}"
		elif self.name_block2:
			return self.name_block2
		else:
			return str(self.id)
		
	def full_name(self):
		if self.name_block and self.name_block2 and self.name_block3:
			return f"{self.name_block} {self.name_block2} {self.name_block3}"
		elif self.name_block and self.name_block2:
			return f"{self.name_block} {self.name_block2}"
		elif self.name_block2 and self.name_block3:
			return f"{self.name_block2} {self.name_block3}"
		elif self.name_block2:
			return self.name_block2
		else:
			return str(self.id)
	

	# переопределение названий
	class Meta:
		verbose_name = "Авторы книг"
		verbose_name_plural = "Авторы книг"
		ordering = ["-created_at"]



class Book (models.Model):

	name_block = models.CharField(u'Название книги', max_length=255, unique=False, null=False, blank=False)
	book_cat = models.ForeignKey('Book_cat', verbose_name='книга относится к категории', default='',  null=True, on_delete=models.CASCADE,)
	opisanie_full = CKEditor5Field(verbose_name='Описание  полное',default='', config_name='extends', null=True, blank=True)
	opisanie_mini = CKEditor5Field(verbose_name='Описание краткое',default='', config_name='extends', null=True, blank=True)
	book_slug = models.SlugField(unique=True, max_length=255,  verbose_name='Url', db_index=True)
	image = models.ImageField(verbose_name='Картинка',upload_to='prostopages',  null=True, blank=True)
	image2 = models.ImageField(verbose_name='Картинка-2',upload_to='prostopages',  null=True, blank=True)
	avtors = models.ManyToManyField('Book_avtor', verbose_name='Автор книги', blank=True, symmetrical=False, related_name='avtor_book')
	price = models.DecimalField(max_digits=6, decimal_places=0, default=0, verbose_name="Цена", null=True, blank=True)
	old_price = models.DecimalField(max_digits=6, decimal_places=0, default=0, verbose_name="Цена без акции", null=True, blank=True)
	procent = models.DecimalField(max_digits=6, decimal_places=0, default=0, verbose_name="Процент скидки", null=True, blank=True)
	skidka = models.DecimalField(max_digits=6, decimal_places=0, default=0, verbose_name="Скидка в рублях", null=True, blank=True)
	file = models.FileField(verbose_name='Файл fb2', upload_to= 'book_files',  null=True, blank=True)
	# file2 = models.FileField(verbose_name='Файл epub', upload_to= 'book_files',  null=True, blank=True)
	# file3 = models.FileField(verbose_name='Файл RTF', upload_to= 'book_files',  null=True, blank=True)
	# file4 = models.FileField(verbose_name='Файл Mobi', upload_to= 'book_files',  null=True, blank=True)
	futured = models.BooleanField(default=True,verbose_name='Будущее',)
	special = models.BooleanField(default=True,verbose_name='Спешл',)
	bestseller = models.BooleanField(default=True,verbose_name='Бестселлер',)
	latest = models.BooleanField(default=True,verbose_name='Последние',)
	active = models.BooleanField(default=True,verbose_name='Активность',)
	created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="Created at")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
	template_name = models.CharField(('Выбор шаблона'),max_length=70,blank=True,)
	uploaded_by = models.ForeignKey(User,verbose_name = 'Автор загрузки',on_delete = models.SET_NULL,null = True,
									blank = True,related_name = 'uploaded_books')

	def __str__(self):
		return self.name_block

	def get_absolute_url(self):
		return "/catalog/%s/%s/" % (self.book_cat.book_cat_slug,self.book_slug,)


	# переопределение названий
	class Meta:
		verbose_name = "Книги"
		verbose_name_plural = "Книги"
		ordering = ["-created_at"]

	def save(self, *args, **kwargs):
		# Расчет скидки и процента скидки
		if self.old_price and self.price:
			self.skidka = self.old_price - self.price
			self.procent = (self.skidka / self.old_price) * 100
		super(Book, self).save(*args, **kwargs)

	def image_img(self,):
		if self.image:
			return mark_safe('<a href="{0}" target="_blank"><img src="{0}" width="100" /></a>' .format(self.image.url))
		else:
			return '(Нет изображения)'
	image_img.short_description = 'Картинка'

	def get_img_tovar_thumbnail(self):
		if self.image:
			a = self.image
			im = get_thumbnail(a, 'x115', format="WEBP", crop='center', )
			im2 = "/media/"+str(im)
			return str(im2)
		else:
			pass

	def get_img_tovar_thumbnail2(self):
		if self.image2:
			a = self.image2
			im = get_thumbnail(a, 'x115', format="WEBP", crop='center', )
			im2 = "/media/"+str(im)
			return str(im2)
		else:
			pass

	def get_img_tovar_thumbnail3(self):
		if self.image:
			a = self.image
			im = get_thumbnail(a, 'x350', format="WEBP", crop='center', )
			im2 = "/media/"+str(im)
			return str(im2)
		else:
			pass

	def get_img_tovar_thumbnail4(self):
		if self.image2:
			a = self.image2
			im = get_thumbnail(a, 'x350', format="WEBP", crop='center', )
			im2 = "/media/"+str(im)
			return str(im2)
		else:
			pass





# class BookFile(models.Model):

# 	book = models.ForeignKey(Book, verbose_name='Выбранная книга', blank=True, null=True ,  on_delete=models.SET_NULL,
# 						   related_name='bookfile')

# 	name = models.CharField(verbose_name='Название', max_length=255, blank=True, null=True, )

# 	created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="Created at")
# 	updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
	
# 	class Meta:
# 		verbose_name = "Файл книги"
# 		verbose_name_plural = "Файл книги"
# 		ordering = ["-created_at"]

# 	def __str__(self):
# 		return f"{self.name}"
	




class OtzivBook(models.Model):

	rayting = models.IntegerField(
		validators=[
			MaxValueValidator(5),
			MinValueValidator(0),
		],
		verbose_name='Интересно',
		blank=True,
		null=True
	)
	rayting2 = models.IntegerField(
		validators=[
			MaxValueValidator(5),
			MinValueValidator(0),
		],
		verbose_name='Цена',
		blank=True,
		null=True
	)
	rayting3 = models.IntegerField(
		validators=[
			MaxValueValidator(5),
			MinValueValidator(0),
		],
		verbose_name='Сюжет',
		blank=True,
		null=True
	)

	rayting_seredina = models.FloatField(
		validators=[
			MaxValueValidator(5),
			MinValueValidator(0),
		],
		verbose_name='Средний рейтинг',
		blank=True,
		null=True
	)

	name_aftor = models.CharField(
		u'Имя автора',  max_length=255, unique=False, null=False, blank=False)
	
	book = models.ForeignKey(Book, on_delete=models.SET_NULL,
	                          blank=True, null=True, verbose_name='выбрать товар по id',)

	otziv_plus = CKEditor5Field(
		verbose_name='Плюсы', default='', null=True, blank=True, config_name='extends')
	
	otziv_minus = CKEditor5Field(
		verbose_name='Минусы', default='', null=True, blank=True, config_name='extends')

	opisanie = CKEditor5Field(
		verbose_name='Комментарий', default='', null=True, blank=True, config_name='extends')


	zakazchik = models.ForeignKey(User, verbose_name='Автор',max_length=255, null=True, blank=True, on_delete=models.SET_NULL,)


	active = models.BooleanField(default=True, verbose_name='Активность',)
	created_at = models.DateTimeField(
		auto_now_add=True, null=True, blank=True, verbose_name="Created at")
	updated_at = models.DateTimeField(
		verbose_name="Перезаписать дату отзыва", null=True, blank=True, )
	#updated_at.editable=True

	def __str__(self):
		return str(self.pk)

	# переопределение названий

	class Meta:
		verbose_name = "Отзыв на книгу"
		verbose_name_plural = "Отзывы на книги"
		ordering = ["-id"]

app/book/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 
from django.core.exceptions import ValidationError 
from django.forms.fields import EmailField 
from django.forms.forms import Form 
from .models import Book
import os
from bs4 import BeautifulSoup

class book_reader:
    def __init__(self, file):
        self.file = file
        self.book = []
        with open(self.file, 'r', encoding='utf-8') as file:
            file = file.readlines()
            _book = []
            for line in file:
                _book.append(line.lstrip())
            for line in file:
                _book.append(line.replace('<p>', '').replace('</p>','\n'))
            for line in _book:
                self.book.append(line.strip('\n'))

    @property
    def get_description(self):
        _description = []
        for line in self.book:
            if line.startswith('<description>'):
                line_index = self.book.index(line)
                for line in self.book[line_index:]:
                    _description.append(line)
                    if line.startswith('</description>'):
                        break

        description = {}
        for line in _description:
            if line.startswith('<book-name>'):
                description['book-title'] = line.lstrip('<book-name>').rstrip('</book-name>')
            elif line.startswith('<book-title>'):
                description['book-title'] = line.lstrip('<book-title>').rstrip('</book-title>')
            elif line.startswith('<author>'):
                a = _description.index(line)
                for i in self.book[a:]:
                    if i.startswith('<first-name>'):
                        description['autor-first-name'] = i.lstrip('<first-name>').rstrip('</first-name>')
                    if i.startswith('<middle-name>'):
                        description['autor-middle-name'] = i.lstrip('<middle-name>').rstrip('</middle-name>')
                    if i.startswith('<last-name>'):
                        description['autor-last-name'] = i.lstrip('<last-name>').rstrip('</last-name>')
                    if i.startswith('</author>'):
                        break
            elif line.startswith('<annotation>'):
                annotation = []
                line_index = self.book.index(line)
                for line in self.book[line_index:]:
                    annotation.append(line)
                    if line.startswith('</annotation>'):
                        break
                description['annotation'] = ''.join(annotation).replace('<empty-line/>', '\n').replace('<annotation>', '').replace('</annotation>', '')

        return description

    def get_chapters_title(self):
        chapters = []
        for index, value in enumerate(self.book):
            if value.startswith('<title>'):
                a = {index : self.book[index+1].lstrip('<p>').rstrip('</p>').lstrip('strong>').rstrip('</strong')}
                chapters.append(a)

        return chapters
class BookUploadForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name_block', 'book_slug', 'book_cat', 
                   
                     'image','image2', 
                     'opisanie_mini',
                    #  'price', 'old_price', 
                     'file']
        
        # opisanie_mini = forms.CharField(widget=forms.Textarea(attrs={
        #     'rows': 3,
        #     # 'cols': 80,
        #     'class' : 'form-control',
        # }))

        # name_block = forms.CharField(widget=forms.TextInput(attrs={
        #     'class' : 'form-control',
        # }))
        # book_slug = forms.CharField(widget=forms.TextInput(attrs={
        #     'class' : 'form-control',
        # }))


class UserForm(UserCreationForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ('first_name','last_name', 'username', 'email', 'password1' ,'password2' )

app/book/templates/book/blog_full.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
{% include "header.html" %}

<div class="wrap-breadcrumb parallax-breadcrumb">
	<div class="container"></div>
</div>

<div class="container">

	<div class="row">

		{% include "left.html" %}

		<div id="content" class="col-sm-9  single-blog">
			<ul class="breadcrumb">

				<li><a href="/"><i class="fa fa-home"></i></a></li>

				<li><a href="/blog/">Блог</a></li>

				<li>{{blog.name_block}}</li>

			</ul>
			<h1>{{blog.name_block}}</h1>

			{% if blog.image %}
			<div class="blog-img">
				<img src="/media/{{blog.image}}"
			alt="{{blog.name_block}}" title="{{blog.name_block}}" class="img-thumbnail">
			</div>
			{% endif %}


			<div class="blog-date">{{ blog.created_at|date:"j" }} 
						{{ blog.created_at|date:"F" }} {{ blog.created_at|date:" Y" }}</div>
			<div>{{blog.text_block|safe}}</div>
		





<div class="box blogs">
					
		<div class="box-head">
			<div class="box-heading">Блог</div>
		</div>
		<div class="box-content">
				
			<div class="customNavigation">
					<a class="fa prev czblog_prev"></a>
					<a class="fa next czblog_next"></a>
				</div>


			
						
			<div class="box-product  owl-carousel blogcarousel " id="blog-carousel">
				 
					{% for blog in blog_r.all %}
					
					{% include "blog_prewie.html" %}
					
					{% endfor %}
				 
				   
			</div>
			<div class="buttons text-center">
				<button type="button" onclick="location='indexc295.html?route=information/blogger/blogs';" class="btn btn-primary">See all Blogs</button>
			</div>
		</div>
</div>
<span class="blog_default_width" style="display:none; visibility:hidden"></span>

<script type="text/javascript"><!--

$(document).ready(function(){
	$('.blogcarousel').owlCarousel({
		items: 3,
		singleItem: false,
		navigation: false,
		pagination: false,
		itemsDesktop : [1199,2],
		itemsDesktopSmall :	[991,2],
		itemsTablet :	[575,1]
	});
	// Custom Navigation Events
	$(".czblog_next").click(function(){
		$('.blogcarousel').trigger('owl.next');
	})
	$(".czblog_prev").click(function(){
		$('.blogcarousel').trigger('owl.prev');
	});	
});	
--></script>


	</div>
</div>
</div>

{% include "footer.html" %}
{% endblock %}

app/book/templates/book/book_reader_fb2.html
{% extends "base.html" %}

{% block content %}
    <h1>Читать книгу {{ book.name_block }}</h1>
    <div id="fb2-content">{{ book_content }}</div>
{% endblock %}

app/book/templates/book/book_upload.html
<form action="{% url 'book-upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

app/book/templates/book/user_profile.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
{% include "header.html" %}


<style>
    .input-file-row {
	display: inline-block;
}
.input-file {
	position: relative;
	display: inline-block;
}
.input-file span {
	position: relative;
	display: inline-block;
	cursor: pointer;
	outline: none;
	text-decoration: none;
	font-size: 14px;
	vertical-align: middle;
	color: rgb(255 255 255);
	text-align: center;
	border-radius: 4px;
	background-color: #e56220;
	line-height: 22px;
	height: 40px;
	padding: 10px 20px;
	box-sizing: border-box;
	border: none;
	margin: 0;
	transition: background-color 0.2s;
}
.input-file input[type=file] {
	position: absolute;
	z-index: -1;
	opacity: 0;
	display: block;
	width: 0;
	height: 0;
}
 
/* Focus */
.input-file input[type=file]:focus + span {
	box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
}
 
/* Hover/active */
.input-file:hover span {
	background-color: #e37f4c;
}
.input-file:active span {
	background-color: #e56220;
}
 
/* Disabled */
.input-file input[type=file]:disabled + span {
	background-color: #eee;
}
 
/* Список c превью */
.input-file-list {
	padding: 10px 0;
}
.input-file-list-item {
	display: inline-block;
	margin: 0 15px 15px;
	width: 150px;
	vertical-align: top;
	position: relative;
}
.input-file-list-item img {
	width: 150px;
}
.input-file-list-name {
	text-align: center;
	display: block;
	font-size: 12px;
	text-overflow: ellipsis;
	overflow: hidden;
}
.input-file-list-remove {
	color: #fff;
	text-decoration: none;
	display: inline-block;
	position: absolute;
	padding: 0;
	margin: 0;
	top: 5px;
	right: 5px;
	background: #ff0202;
	width: 16px;
	height: 16px;
	text-align: center;
	line-height: 16px;
	border-radius: 50%;
}


.select {
  position: relative;
  min-width: 200px;
}
.select svg {
  position: absolute;
  right: 12px;
  top: calc(50% - 3px);
  width: 10px;
  height: 6px;
  stroke-width: 2px;
  stroke: #9098a9;
  fill: none;
  stroke-linecap: round;
  stroke-linejoin: round;
  pointer-events: none;
}
.select select {
  -webkit-appearance: none;
  padding: 7px 40px 7px 12px;
  width: 100%;
  border: 1px solid #e8eaed;
  border-radius: 5px;
  background: #fff;
  box-shadow: 0 1px 3px -2px #9098a9;
  cursor: pointer;
  font-family: inherit;
  font-size: 16px;
  transition: all 150ms ease;
}
.select select:required:invalid {
  color: #5a667f;
}
.select select option {
  color: #223254;
}
.select select option[value=""][disabled] {
  display: none;
}
.select select:focus {
  outline: none;
  border-color: #07f;
  box-shadow: 0 0 0 2px rgba(0,119,255,0.2);
}
.select select:hover + svg {
  stroke: #07f;
}
.sprites {
  position: absolute;
  width: 0;
  height: 0;
  pointer-events: none;
  user-select: none;
}

.img_wrp {
    display: flex;
    flex-wrap: wrap;
    background: #efefef;
    margin-bottom: 10px;
    padding: 10px;
    border-radius: 5px;
}

.img {
    width: 50px;
    margin-right: 15px;
}

.img img{
    width: 100%;
}

</style>


<div class="wrap-breadcrumb parallax-breadcrumb">
	<div class="container"></div>
</div>

<div class="container">

	<div class="row">

		{% include "left.html" %}

		<div id="content" class="col-sm-9  single-blog">
			<ul class="breadcrumb">

				<li><a href="/"><i class="fa fa-home"></i></a></li>

				<li>Профиль пользователя</li>

			</ul>


			<h1>Привет, {{ user }}! </h1>

       <div class="well">
            
               <div class="">
            <div class="card">
                <div class="card-header">
                    <h4>Загруженные книги:</h4>
                </div>
                <div class="card-body">
                    {% if user_books %}
                       
                            {% for book in user_books %}
                               
                                    <div class="img_wrp">
                                        <div class="img"><img src="/media/{{ book.image }}" alt="{{ book.name_block }}"></div>

                                        <div class="img_r">
                                            <a href="{% url 'book_full' book.book_cat.book_cat_slug book.book_slug %}">  {{ book.name_block }}</a><br>
                                        
                                            <a href="{{ book.file.url }}" target="_blank">Скачать</a>
                                        
                                            <a href="{% url 'book_full' book.book_cat.book_cat_slug book.book_slug %}prewie/" target="_blank">Читать</a>
                                        </div>
                                    </div>
                               
                            {% endfor %}
                        
                    {% else %}
                        <p>Еще нет загруженных книг</p>
                    {% endif %}
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h1>Загрузка книги</h1>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                   


                            <div>
                                <label for="id_name_block">Название книги</label><br>
                                <input type="text" class="form-control" name="name_block" maxlength="255" required="" id="id_name_block">
                            </div>

                        
                            <div>
                                <label for="id_book_slug">Url</label><br>
                                <input type="text" class="form-control" name="book_slug" maxlength="255" required="" id="id_book_slug">
                            </div>

                           
                            <div>
                                <label for="id_book_cat">Книга относится к категории</label>
                            </div>


<label class="select" for="slct">
  <select id="slct" required="required" name="book_cat" id="id_book_cat">
 
  <option value="1">Приключение</option>

  <option value="2">Сказки</option>

  <option value="3">Фантастика</option>

  <option value="4">Философия</option>

  <option value="5">Кулинария</option>

  <option value="6">Дети</option>

  <option value="7">Психология</option>

  </select>
  <svg>
    <use xlink:href="#select-arrow-down"></use>
  </svg>
</label>
<!-- SVG Sprites-->
<svg class="sprites">
  <symbol id="select-arrow-down" viewbox="0 0 10 6">
    <polyline points="1 1 5 5 9 1"></polyline>
  </symbol>
</svg>




                            

                           

                        
                          
                            <div> <label for="id_image">Картинка</label></div>
                        
                            <div class="input-file-row">
                                <label class="input-file">
                                    <input type="file" name="image" accept="image/*" id="id_image">		
                                    <span>Выберите файл</span>
                                </label>
                                <div class="input-file-list"></div>  
                            </div>

                        
                            <div> <label for="id_image2">Картинка-2</label></div>
                        
                            <div class="input-file-row">
                                <label class="input-file">
                                    <input type="file" name="image2" accept="image/*"  id="id_image2">		
                                    <span>Выберите файл</span>
                                </label>
                                <div class="input-file-list"></div>  
                            </div><br>

                        
                           
                            <div><label for="id_opisanie_mini">Описание краткое</label></div> 
                       
                            <textarea class="form-control" name="opisanie_mini" class="" id="id_opisanie_mini"></textarea><br>
                            
                            <div>
                                <label for="id_file">Файл fb2</label>
                            </div>

                            <div class="input-file-row">
                                <label class="input-file">
                                    <input type="file" name="file">		
                                    <span>Выберите файл</span>
                                </label>
                                <div class="input-file-list"></div>  
                            </div>
                            
                            <br>
                        <button type="submit" class="btn btn-primary">Загрузить</button>
                    </form>
                </div>
            </div>
        </div>


    </div>

        {% comment %}  {% endcomment %}

		</div>


	</div>
</div>


<script>
    var dt = new DataTransfer();
 
$('.input-file input[type=file]').on('change', function(){
    let $files_list = $(this).closest('.input-file').next();
    $files_list.empty();
 
    for(var i = 0; i < this.files.length; i++){
        let file = this.files.item(i);
        dt.items.add(file);    
   
        let reader = new FileReader();
        reader.onloadend = function(){
            let file_html;
            if(file.type.match('image.*')) {
                file_html = '<div class="input-file-list-item">' +
                    '<img class="input-file-list-img" src="' + reader.result + '">' +
                    '<span class="input-file-list-name">' + file.name + '</span>' +
                    '<a href="#" onclick="removeFilesItem(this); return false;" class="input-file-list-remove">x</a>' +
                '</div>';
            } else {
                // Здесь можно добавить другой HTML для неизображений
                file_html = '<div class="input-file-list-item">' +
                    '<span class="input-file-list-name">' + file.name + '</span>' +
                    '<a href="#" onclick="removeFilesItem(this); return false;" class="input-file-list-remove">x</a>' +
                '</div>';
            }
            $files_list.append(file_html); 
        }
        reader.readAsDataURL(file);
    };
    this.files = dt.files;
});
 
function removeFilesItem(target){
	let name = $(target).prev().text();
	let input = $(target).closest('.input-file-row').find('input[type=file]');	
	$(target).closest('.input-file-list-item').remove();	
	for(let i = 0; i < dt.items.length; i++){
		if(name === dt.items[i].getAsFile().name){
			dt.items.remove(i);
		}
	}
	input[0].files = dt.files;  
}
</script>


{% include "footer.html" %}
{% endblock %}